### PR TITLE
issue #39; support ann name with digit; add type

### PR DESCRIPTION
**Pull request by GregSilverman**
Still need to add a test (I will do this as time permits), but this worked in all cases. 

Also, found bug when digit in annotation type name: added regex for digits to `_string_to_valid_classname`.

Also, added missing types to type system definitions:

` "org.apache.uima.examples.SourceDocumentInformation"`

### CODE REVIEW

**Comment by jcklie** [comment]
Thank you very much for the pull request! I will look into it next week, I still am on the road. Sorry again for the delay.

**Comment by GregSilverman** [comment]
I need to tweak this a bit. Instead of using a list to store the array, I need to have it represented as a string of strings with spaces between each element in the string. This was breaking downstream in our postprocessing pipeline.

**Comment by jcklie** [comment]
Thank you again for your pull request and the interest in cassis! I used your code as an inspiration for that feature. I created a pull request on my own #50 . Some questions: why do you want to not strip numbers from type names? SourceDocumentInformation is not exactly a builtin type, it comes from `org.apache.uima.examples`, therefore I do not want to add it as a builtin type.

**Comment by GregSilverman** [comment]
We have types with numbers in the name (e.g, `biomedicus.v2.UmlsConcept`). I found that when the number was being stripped then I could not query for this type, which is why I added that to the regex. 

That's fine about the other type. We'll just maintain our own version of the typesystem file.

**Comment by reckart** [comment]
> Some questions: why do you want to not strip numbers from type names?

Why should anything be stripped from type names?

**Comment by jcklie** [comment]
I convert type names to python class names, so I need to e.g. remove the dots.

**Comment by reckart** [comment]
Doesn't python have a concept of namespaces/packages?

**Pull request closed without merging**
